spring:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
    h2:
      console:
        enabled: false
    jpa:
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          hbm2ddl:
            auto: none

springdoc:
  api-docs:
    path: /v3/swagger-ui.html
  swagger-ui:
    path: /v3/api-docs
