CREATE TABLE IF NOT EXISTS BRAND
(
    ID   INTEGER      NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRICES
(
    ID         VARCHAR(255)   NOT NULL,
    PRODUCT    INTEGER        NOT NULL,
    BRAND_ID   INTEGER        NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    PRICE_LIST INT            NOT NULL,
    PRIORITY   INT            NOT NULL,
    CURRENCY   VARCHAR(3)     NOT NULL,
    START_DATE DATETIME       NOT NULL,
    END_DATE   DATETIME       NOT NULL,
    PRIMARY KEY (ID),
    constraint "BRAND_BRAND_ID_FK"
        foreign key (BRAND_ID) references BRAND
);